export const selectData = {
    "recruitment" : [
        { value: 'frontend', label: '프론트엔드' },
        { value: 'backend', label: '백엔드' },
        { value: 'android', label: '안드로이드' },
        { value: 'ios', label: 'IOS' },
        { value: 'design', label: '디자인' },
    ],
    "technique" : [
        { value: 'react', label: 'React' },
        { value: 'typescript', label: 'TypeScript' },
        { value: 'javascript', label: 'JavaScript' },
        { value: 'vue', label: 'Vue' },
        { value: 'nextjs', label: 'Nextjs' },
        { value: 'nodejs', label: 'Nodejs' },
        { value: 'java', label: 'Java' },
        { value: 'spring', label: 'Spring' },
        { value: 'mysql', label: 'MySQL' },
        { value: 'python', label: 'Python' },
        { value: 'mongodb', label: 'MongoDB' },
        { value: 'django', label: 'Django' },
        { value: 'php', label: 'php' },
        { value: 'figma', label: 'Figma' },
        { value: 'reactnative', label: 'Reactnative' },
        { value: 'kotlin', label: 'Kotlin' },
        { value: 'swift', label: 'Swift' },
    ],
    "proficiency" : [
        { value: 'junior', label: '주니어' },
        { value: 'senior', label: '시니어' },
        { value: 'master', label: '마스터' },
    ],
}